{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Erreur 200",
   "type": "stat",
   "description": "Nombre d'erreur 200 sur une intervalle de 24h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({job=\"fluent-bit\"} |= `` | json ConnectionId, StatusCode , Method, Path | StatusCode = `200` [24h]))",
     "legendFormat": "StatusCode",
     "maxLines": 401
    }
   ]
  },
  {
   "title": "Erreur 200",
   "type": "piechart",
   "description": "Nombre d'erreur 200 sur une intervalle de 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (rate({job=\"fluent-bit\"} |= `` | json ConnectionId, StatusCode , Method, Path | StatusCode = `200` [24h]))",
     "legendFormat": "StatusCode",
     "maxLines": 401
    },
    {
     "expr": "count by(job) (rate({job=\"fluent-bit\"} |= `` | json ConnectionId, StatusCode , Method, Path | StatusCode != `200` [24h]))",
     "legendFormat": "StatusCode",
     "maxLines": 401
    }
   ]
  },
  {
   "title": "Erreur 500",
   "type": "stat",
   "description": "Nombre d'erreur 500 sur une intervalle de 24h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({job=\"fluent-bit\"} |= `` | json ConnectionId, StatusCode , Method, Path | StatusCode = `500` [24h]))",
     "legendFormat": "StatusCode",
     "maxLines": 401
    }
   ]
  },
  {
   "title": "Erreur 401",
   "type": "timeseries",
   "description": "Nombre d'erreur 401 sur une intervalle de 24h",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(rate({job=\"fluent-bit\"} |= `` | json ConnectionId, StatusCode , Method, Path | StatusCode = `401` [24h]))",
     "legendFormat": "StatusCode",
     "maxLines": 401
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\"} |= ``"
    }
   ]
  }
 ]
}